package org.campagnelab.mps.XChart.helpers;

/*Generated by MPS */

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import java.util.ArrayList;
import java.io.IOException;

public class ColumnLoader {
  public static double[] load(String filename, String columnName, String delimiter) {
    BufferedReader reader = null;
    if (filename == null) {
      return new double[0];
    }
    try {
      reader = new BufferedReader(new FileReader(new File(filename)));
      String header = reader.readLine();
      String[] columns = header.split(delimiter);
      int index = -1;
      for (String col : columns) {
        index += 1;
        if (columnName.equalsIgnoreCase(col)) {
          break;
        }
      }
      if (index == -1) {
        return new double[0];
      }
      String line = null;
      ArrayList<String> list = new ArrayList<String>();

      while ((line = reader.readLine()) != null) {
        String[] values = line.split(delimiter);
        list.add(values[index]);
      }
      double[] result = new double[list.size()];
      int i = 0;
      for (String element : list) {
        double value;
        try {
          value = Double.parseDouble(element);
          if (value != value) {
            value = 0;
          }
        } catch (NumberFormatException e) {
          // replace NaNs with zero because XChart cannot deal with them. 
          value = 0.0;
        }
        result[i++] = value;
      }
      return result;
    } catch (IOException exception) {
      return new double[0];
    } finally {
      try {
        if (reader != null) {
          reader.close();
        }
      } catch (IOException e) {
      }
    }
  }
}
