package org.campagnelab.mps.XChart.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import java.io.File;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.campagnelab.mps.XChart.behavior.DelimitedFile__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.campagnelab.mps.XChart.behavior.HasDataToPreserve__BehaviorDescriptor;

public class DelimitedFile_Constraints extends BaseConstraintsDescriptor {
  public DelimitedFile_Constraints() {
    super(MetaAdapterFactory.getConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b92L, "org.campagnelab.mps.XChart.structure.DelimitedFile"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a72L, "path"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a72L), this) {
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "path";
        {
          File file = new File((SPropertyOperations.getString(propertyValue)));
          if (!(file.exists())) {
            return;
          }
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a72L, "path"), (SPropertyOperations.getString(propertyValue)));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), file.getName());
          List<SNode> previousColumns = ListSequence.fromList(new ArrayList<SNode>());
          ListSequence.fromList(previousColumns).addSequence(ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))));
          ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))).clear();
          for (String col : DelimitedFile__BehaviorDescriptor.parseColumns_id37GCX3DasUd.invoke(node)) {
            if (col == null) {
              continue;
            }
            SNode c = SModelOperations.createNewNode(SNodeOperations.getModel(node), null, MetaAdapterFactory.getConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c9a6fL, "org.campagnelab.mps.XChart.structure.Column"));
            SPropertyOperations.set(c, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), col);
            DelimitedFile__BehaviorDescriptor.assignColumnType_id4m7W1CEBXv9.invoke(node, c);
            if (SNodeOperations.isInstanceOf(node, MetaAdapterFactory.getInterfaceConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e25c753b59a0fe7L, "org.campagnelab.mps.XChart.structure.HasDataToPreserve"))) {
              HasDataToPreserve__BehaviorDescriptor.newColumAdded_id1S_LPePBAim.invoke(SNodeOperations.cast(node, MetaAdapterFactory.getInterfaceConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e25c753b59a0fe7L, "org.campagnelab.mps.XChart.structure.HasDataToPreserve")), c, previousColumns);
            }
            ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))).addElement(c);
          }
        }
      }
    });
    return properties;
  }
}
