package org.campagnelab.mps.XChart.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SPropertyId;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import java.io.File;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.campagnelab.mps.XChart.behavior.DelimitedFile_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class DelimitedFile_Constraints extends BaseConstraintsDescriptor {
  public DelimitedFile_Constraints() {
    super(MetaIdFactory.conceptId(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b92L));
  }
  @Override
  protected Map<SPropertyId, PropertyConstraintsDescriptor> getNotDefaultSProperties() {
    Map<SPropertyId, PropertyConstraintsDescriptor> properties = new HashMap<SPropertyId, PropertyConstraintsDescriptor>();
    properties.put(MetaIdFactory.propId(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a72L), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a72L), this) {
      @Override
      public boolean hasOwnSetter() {
        return true;
      }
      @Override
      public void setValue(SNode node, String propertyValue) {
        String propertyName = "path";
        {
          File file = new File((SPropertyOperations.getString(propertyValue)));
          if (!(file.exists())) {
            return;
          }
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a72L, "path"), (SPropertyOperations.getString(propertyValue)));
          SPropertyOperations.set(node, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), file.getName());
          List<SNode> previousColumns = ListSequence.fromList(new ArrayList<SNode>());
          ListSequence.fromList(previousColumns).addSequence(ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))));
          ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))).clear();
          for (String col : DelimitedFile_Behavior.call_parseColumns_3597430320022539917(node)) {
            if (col == null) {
              continue;
            }
            SNode c = SModelOperations.createNewNode(SNodeOperations.getModel(node), null, SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c9a6fL, "org.campagnelab.mps.XChart.structure.Column")));
            SPropertyOperations.set(c, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), col);
            DelimitedFile_Behavior.call_assignColumnType_5010237105647900617(node, c);
            if (SNodeOperations.isInstanceOf(node, MetaAdapterFactory.getInterfaceConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e25c753b59a0fe7L, "org.campagnelab.mps.XChart.structure.HasDataToPreserve"))) {
              BehaviorReflection.invokeVirtual(Void.class, SNodeOperations.cast(node, MetaAdapterFactory.getInterfaceConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e25c753b59a0fe7L, "org.campagnelab.mps.XChart.structure.HasDataToPreserve")), "virtual_newColumAdded_2172361557619401878", new Object[]{c, previousColumns});
            }
            ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c8b97L, 0x1e924e67df2c9a74L, "columns"))).addElement(c);
          }
        }
      }
    });
    return properties;
  }
}
