package org.campagnelab.mps.XChart.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class Doubles_Constraints extends BaseConstraintsDescriptor {
  public Doubles_Constraints() {
    super("org.campagnelab.mps.XChart.structure.Doubles");
  }
}
