package org.campagnelab.mps.XChart.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class Doubles_Constraints extends BaseConstraintsDescriptor {
  public Doubles_Constraints() {
    super(MetaIdFactory.conceptId(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2c9de7L));
  }
}
