package org.campagnelab.mps.XChart.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class Histogram_Constraints extends BaseConstraintsDescriptor {
  public Histogram_Constraints() {
    super("org.campagnelab.mps.XChart.structure.Histogram");
  }
}
