package org.campagnelab.mps.XChart.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class Page_Constraints extends BaseConstraintsDescriptor {
  public Page_Constraints() {
    super("org.campagnelab.mps.XChart.structure.Page");
  }
}
