package org.campagnelab.mps.XChart.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum ChartTheme {
  GGPlot2("GGPlot2 ", "GGPlot2"),
  MatLab("MatLab", "MatLab"),
  XChart("XChart", "XChart");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private ChartTheme(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<ChartTheme> getConstants() {
    List<ChartTheme> list = ListSequence.fromList(new LinkedList<ChartTheme>());
    ListSequence.fromList(list).addElement(ChartTheme.GGPlot2);
    ListSequence.fromList(list).addElement(ChartTheme.MatLab);
    ListSequence.fromList(list).addElement(ChartTheme.XChart);
    return list;
  }
  public static ChartTheme getDefault() {
    return ChartTheme.XChart;
  }
  public static ChartTheme parseValue(String value) {
    if (value == null) {
      return ChartTheme.getDefault();
    }
    if (value.equals(ChartTheme.GGPlot2.getValueAsString())) {
      return ChartTheme.GGPlot2;
    }
    if (value.equals(ChartTheme.MatLab.getValueAsString())) {
      return ChartTheme.MatLab;
    }
    if (value.equals(ChartTheme.XChart.getValueAsString())) {
      return ChartTheme.XChart;
    }
    return ChartTheme.getDefault();
  }
}
