package org.campagnelab.mps.XChart.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("org.campagnelab.mps.XChart.structure.Chart").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").abstract_().alias("chart", "A Chart").create();
      case 1:
        return new ConceptDescriptorBuilder("org.campagnelab.mps.XChart.structure.Column").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").create();
      case 2:
        return new ConceptDescriptorBuilder("org.campagnelab.mps.XChart.structure.ColumnToDoubles").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "org.campagnelab.mps.XChart.structure.Doubles").references("file", "column").alias("column-to-double", "").create();
      case 3:
        return new ConceptDescriptorBuilder("org.campagnelab.mps.XChart.structure.DataFile").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").properties("path").children(new String[]{"columns"}, new boolean[]{true}).alias("", "A data file").create();
      case 4:
        return new ConceptDescriptorBuilder("org.campagnelab.mps.XChart.structure.DelimitedFile").super_("org.campagnelab.mps.XChart.structure.DataFile").parents("org.campagnelab.mps.XChart.structure.DataFile").properties("delimitor").alias("delimited-file", "File with column delimited by some character").create();
      case 5:
        return new ConceptDescriptorBuilder("org.campagnelab.mps.XChart.structure.Doubles").interface_().create();
      case 6:
        return new ConceptDescriptorBuilder("org.campagnelab.mps.XChart.structure.Histogram").super_("org.campagnelab.mps.XChart.structure.Chart").parents("org.campagnelab.mps.XChart.structure.Chart").children(new String[]{"values", "frequencies"}, new boolean[]{false, false}).alias("histogram", "").create();
      case 7:
        return new ConceptDescriptorBuilder("org.campagnelab.mps.XChart.structure.Tsvfile").super_("org.campagnelab.mps.XChart.structure.DelimitedFile").parents("org.campagnelab.mps.XChart.structure.DelimitedFile").alias("TSV", "Tab delimited file").create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"org.campagnelab.mps.XChart.structure.Chart", "org.campagnelab.mps.XChart.structure.Column", "org.campagnelab.mps.XChart.structure.ColumnToDoubles", "org.campagnelab.mps.XChart.structure.DataFile", "org.campagnelab.mps.XChart.structure.DelimitedFile", "org.campagnelab.mps.XChart.structure.Doubles", "org.campagnelab.mps.XChart.structure.Histogram", "org.campagnelab.mps.XChart.structure.Tsvfile"};
}
