package org.campagnelab.mps.XChart.sandbox;

/*Generated by MPS */

import java.util.ArrayList;
import com.xeiam.xchart.Chart;
import com.xeiam.xchart.ChartBuilder;
import com.xeiam.xchart.StyleManager;
import org.campagnelab.mps.XChart.helpers.ColumnLoader;
import org.campagnelab.mps.XChart.helpers.BinHelper;
import org.campagnelab.mps.XChart.helpers.DoublesToCollection;
import org.campagnelab.mps.XChart.helpers.CustomSwingWrapper;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class ChartViewer_ScatterPlotTest {
  public static ArrayList<Chart> buildCharts(String... filenames) {
    ArrayList<Chart> charts = new ArrayList<Chart>();
    int filenameIndex = 0;
    int numCharts = 2;
    {
      Chart chart = null;
      String filename = filenames[filenameIndex];
      {
        // Histogram BarChart 

        chart = new ChartBuilder().chartType(StyleManager.ChartType.Bar).width(400).height(400).theme(StyleManager.ChartTheme.GGPlot2).title("Title").xAxisTitle("x").yAxisTitle("y").build();
        chart.getStyleManager().setXAxisMax(Double.parseDouble("200"));
        chart.getStyleManager().setLegendVisible(false);
        chart.getStyleManager().setLegendPosition(StyleManager.LegendPosition.InsideN);
        ArrayList<Double> x = new ArrayList<Double>();
        ArrayList<Double> y = new ArrayList<Double>();
        double[] doubles = ColumnLoader.load(filename, "count-variation-bases", "\t");
        BinHelper.bin(doubles, x, y);
        chart.addSeries("series", x, y);


      }
      if (chart != null) {
        charts.add(chart);
      }
      filenameIndex++;
      if (filenameIndex == numCharts) {
        filenameIndex = 0;
      }
    }
    {
      Chart chart = null;
      String filename = filenames[filenameIndex];
      {
        // ScaterPlot 

        double[] xs = null;
        chart = new ChartBuilder().chartType(StyleManager.ChartType.Scatter).width(400).height(400).theme(StyleManager.ChartTheme.GGPlot2).title("Title").xAxisTitle("x").yAxisTitle("y").build();
        chart.getStyleManager().setXAxisMax(Double.parseDouble("200"));
        chart.getStyleManager().setLegendVisible(false);
        chart.getStyleManager().setLegendPosition(StyleManager.LegendPosition.InsideN);
        chart.addSeries("data", DoublesToCollection.toCollection(ColumnLoader.load(filename, "read-index", "\t")), DoublesToCollection.toCollection(ColumnLoader.load(filename, "count-variation-bases", "\t")));

      }
      if (chart != null) {
        charts.add(chart);
      }
      filenameIndex++;
      if (filenameIndex == numCharts) {
        filenameIndex = 0;
      }
    }
    return charts;
  }



  /**
   * Returns a JFrame with the charts that display the content of the files.
   */
  public static void view(String... filenames) {
    ArrayList<Chart> charts = buildCharts(filenames);
    CustomSwingWrapper wrapper = new CustomSwingWrapper(charts);
    wrapper.setOnClose(JFrame.DISPOSE_ON_CLOSE);
    wrapper.displayChartMatrix();

  }

  /**
   * Returns a JPanel with the charts that display the content of the files.
   */
  public static JPanel panel(String... filenames) {
    ArrayList<Chart> charts = buildCharts(filenames);
    CustomSwingWrapper wrapper = new CustomSwingWrapper(charts);
    return wrapper.getChartMatrixPanel();
  }

  public static void main(String[] args) {
    view(args);
  }


}
