package org.campagnelab.mps.XChart.sandbox;

/*Generated by MPS */

import java.util.ArrayList;
import com.xeiam.xchart.Chart;
import com.xeiam.xchart.ChartBuilder;
import com.xeiam.xchart.StyleManager;
import org.campagnelab.mps.xchart.lib.HelperClasses.DoublesToCollection;
import org.campagnelab.mps.xchart.lib.HelperClasses.ColumnLoader;
import com.xeiam.xchart.SwingWrapper;

public class ChartViewer_SequenceVariations {
  public static void view(String... filenames) {
    ArrayList<Chart> charts = new ArrayList<Chart>();
    int filenameIndex = 0;
    int numCharts = 1;
    {
      Chart chart = null;
      String filename = filenames[filenameIndex];
      {
        double[] xs = null;
        chart = new ChartBuilder().chartType(StyleManager.ChartType.Bar).width(800).height(400).theme(StyleManager.ChartTheme.GGPlot2).title("Title").xAxisTitle("XXX").yAxisTitle("YYY").build();
        chart.addSeries("data", DoublesToCollection.toCollection(ColumnLoader.load(filename, "read-index", "\t")), DoublesToCollection.toCollection(ColumnLoader.load(filename, "count-variation-bases", "\t")));

        chart.addSeries("second", DoublesToCollection.toCollection(ColumnLoader.load(filename, "read-index", "\t")), DoublesToCollection.toCollection(ColumnLoader.load(filename, "count-variation-bases", "\t")));

        chart.addSeries("third", DoublesToCollection.toCollection(ColumnLoader.load(filename, "read-index", "\t")), DoublesToCollection.toCollection(ColumnLoader.load(filename, "count-variation-bases", "\t")));

        chart.getStyleManager().setLegendPosition(StyleManager.LegendPosition.InsideNE);
      }
      if (chart != null) {
        charts.add(chart);
      }
      filenameIndex++;
      if (filenameIndex == numCharts) {
        filenameIndex = 0;
      }
    }

    new SwingWrapper(charts).displayChart();
  }

  public static void main(String[] args) {
    view(args[0]);
  }


}
