package org.campagnelab.mps.XChart.sandbox;

/*Generated by MPS */

import java.util.ArrayList;
import com.xeiam.xchart.Chart;
import com.xeiam.xchart.ChartBuilder;
import com.xeiam.xchart.StyleManager;
import org.campagnelab.mps.XChart.helpers.DoublesToCollection;
import org.campagnelab.mps.XChart.helpers.ColumnLoader;
import org.campagnelab.mps.XChart.helpers.CustomSwingWrapper;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class ChartViewer_SequenceVariations {
  public static ArrayList<Chart> buildCharts(String... filenames) {
    ArrayList<Chart> charts = new ArrayList<Chart>();
    int filenameIndex = 0;
    int numCharts = 1;
    {
      Chart chart = null;
      String filename = filenames[filenameIndex];
      {
        // BarChart 
        double[] xs = null;
        chart = new ChartBuilder().chartType(StyleManager.ChartType.Bar).width(800).height(400).theme(StyleManager.ChartTheme.GGPlot2).title("Title").xAxisTitle("The X Axis, scaled with max X=200").yAxisTitle("Y").build();
        chart.getStyleManager().setXAxisMax(Double.parseDouble("200"));
        chart.getStyleManager().setLegendVisible(true);
        chart.getStyleManager().setLegendPosition(StyleManager.LegendPosition.InsideSW);
        chart.addSeries("data", DoublesToCollection.toCollection(ColumnLoader.load(filename, "read-index", "\t")), DoublesToCollection.toCollection(ColumnLoader.load(filename, "count-variation-bases", "\t")));

      }
      if (chart != null) {
        charts.add(chart);
      }
      filenameIndex++;
      if (filenameIndex == numCharts) {
        filenameIndex = 0;
      }
    }
    return charts;
  }

  /**
   * Returns a JFrame with the charts that display the content of the files.
   */
  public static void view(String... filenames) {
    ArrayList<Chart> charts = buildCharts(filenames);
    CustomSwingWrapper wrapper = new CustomSwingWrapper(charts);
    wrapper.setOnClose(JFrame.DISPOSE_ON_CLOSE);
    wrapper.displayChartMatrix();

  }
  /**
   * Returns a JPanel with the charts that display the content of the files.
   */
  public static JPanel panel(String... filenames) {
    ArrayList<Chart> charts = buildCharts(filenames);
    CustomSwingWrapper wrapper = new CustomSwingWrapper(charts);
    return wrapper.getChartMatrixPanel();
  }
  public static void main(String[] args) {
    view(args);
  }

}
