package org.campagnelab.mps.XChart.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cells.EditorCell_Component;
import javax.swing.JComponent;
import org.campagnelab.mps.XChart.behavior.Chart__BehaviorDescriptor;
import jetbrains.mps.editor.runtime.cells.BigCellUtil;

public class Histogram_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_dnpd9w_a(editorContext, node);
  }
  public EditorCell createInspectedCell(EditorContext editorContext, SNode node) {
    return this.createComponent_dnpd9w_a(editorContext, node);
  }
  private EditorCell createCollection_dnpd9w_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_dnpd9w_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_dnpd9w_a0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_dnpd9w_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_dnpd9w_c0(editorContext, node));
    editorCell.addEditorCell(this.createJComponent_dnpd9w_d0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_dnpd9w_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "histogram of ");
    editorCell.setCellId("Constant_dnpd9w_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createComponent_dnpd9w_b0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "org.campagnelab.mps.XChart.editor.DataSeriesComponent");
    return editorCell;
  }
  private EditorCell createConstant_dnpd9w_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_dnpd9w_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createJComponent_dnpd9w_d0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = EditorCell_Component.createComponentCell(editorContext, node, Histogram_Editor._QueryFunction_JComponent_dnpd9w_a3a(node, editorContext), "_dnpd9w_d0");
    editorCell.setCellId("JComponent_dnpd9w_d0");
    return editorCell;
  }
  private static JComponent _QueryFunction_JComponent_dnpd9w_a3a(final SNode node, final EditorContext editorContext) {
    return (JComponent) Chart__BehaviorDescriptor.getJComponent_id4IRfUGkOim8.invoke(node);
  }
  private EditorCell createComponent_dnpd9w_a(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "org.campagnelab.mps.XChart.editor.ChartDimensions");
    EditorCell bigCell = BigCellUtil.findBigCell(editorCell, node);
    if (bigCell != null) {
      bigCell.setBig(true);
    }
    return editorCell;
  }
}
