package org.campagnelab.mps.XChart.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_6638345083856263985(final PropertyMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "charts", true)).count();
  }

  public static Object propertyMacro_GetPropertyValue_6638345083855581952(final PropertyMacroContext _context) {
    return "ChartViewer_" + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849263626(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "width");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849276542(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "height");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849313523(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "title");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849342641(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") : "x");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849376242(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") : "y");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083855818193(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083855905196(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(0), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083855985425(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(1), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083856041174(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083856041185(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(0), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083856041202(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(1), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083856053754(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(2), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388102(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "width");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388113(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "height");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388126(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "title");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388137(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") : "x");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388161(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") : "y");
  }

  public static Object propertyMacro_GetPropertyValue_568598610958112950(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "dataSeries", true)).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getTargets(it, "values", true);
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, "name").equals("x");
      }
    }), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355534(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "width");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355545(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "height");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355558(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "title");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355569(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") : "x");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355589(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") : "y");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355615(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355626(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(0), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355645(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(1), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355676(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355687(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(0), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355706(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(1), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026355725(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(2), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026458408(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "minY");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026476532(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "maxY");
  }

  public static Object propertyMacro_GetPropertyValue_6642819616966908686(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "minX");
  }

  public static Object propertyMacro_GetPropertyValue_6642819616966911688(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "maxX");
  }

  public static Object propertyMacro_GetPropertyValue_3670852936026972124(final PropertyMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "legend", true) != null);
  }

  public static Object referenceMacro_GetReferent_3670852936027539524(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString_def(SLinkOperations.getTarget(_context.getNode(), "legend", true), "position", "InsideN").toString();
  }

  public static boolean ifMacro_Condition_6638345083855822348(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).count() == 2;
  }

  public static boolean ifMacro_Condition_6638345083856041215(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).count() == 3;
  }

  public static boolean ifMacro_Condition_3670852936026355660(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).count() == 2;
  }

  public static boolean ifMacro_Condition_3670852936026355740(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).count() == 3;
  }

  public static boolean ifMacro_Condition_3670852936026460165(final IfMacroContext _context) {
    return isNotEmptyString(SPropertyOperations.getString(_context.getNode(), "minY"));
  }

  public static boolean ifMacro_Condition_3670852936026476539(final IfMacroContext _context) {
    return isNotEmptyString(SPropertyOperations.getString(_context.getNode(), "maxY"));
  }

  public static boolean ifMacro_Condition_6642819616966908693(final IfMacroContext _context) {
    return isNotEmptyString(SPropertyOperations.getString(_context.getNode(), "minX"));
  }

  public static boolean ifMacro_Condition_6642819616966911695(final IfMacroContext _context) {
    return isNotEmptyString(SPropertyOperations.getString(_context.getNode(), "maxX"));
  }

  public static SNode sourceNodeQuery_3670852936026821849(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "style", true);
  }

  public static SNode sourceNodeQuery_3670852936027012712(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "style", true);
  }

  public static SNode sourceNodeQuery_3670852936026703138(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "style", true);
  }

  public static Iterable<SNode> sourceNodesQuery_6638345083849206800(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "charts", true);
  }

  public static Iterable<SNode> sourceNodesQuery_6638345083855817217(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "dataSeries", true);
  }

  public static Iterable<SNode> sourceNodesQuery_3670852936026355752(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "dataSeries", true);
  }

  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
