package org.campagnelab.mps.XChart.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.generator.template.IfMacroContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_6638345083856263985(final PropertyMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "charts", true)).count();
  }

  public static Object propertyMacro_GetPropertyValue_6638345083855581952(final PropertyMacroContext _context) {
    return "ChartViewer_" + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849263626(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "width");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849276542(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "height");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849313523(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "title");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849342641(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") : "x");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849376242(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") : "y");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083855818193(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083855905196(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(0), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083855985425(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(1), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083856041174(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083856041185(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(0), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083856041202(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(1), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083856053754(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).getElement(2), "doubles", false), "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388102(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "width");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388113(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "style", true), "height");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388126(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "title");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388137(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "xAxisLabel") : "x");
  }

  public static Object propertyMacro_GetPropertyValue_6638345083849388161(final PropertyMacroContext _context) {
    return (SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") != null ? SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "style", true), "yAxisLabel") : "y");
  }

  public static boolean ifMacro_Condition_6638345083855822348(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).count() == 2;
  }

  public static boolean ifMacro_Condition_6638345083856041215(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "values", true)).count() == 3;
  }

  public static SNode sourceNodeQuery_6638345083849451749(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "x", false);
  }

  public static Iterable<SNode> sourceNodesQuery_6638345083849206800(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "charts", true);
  }

  public static Iterable<SNode> sourceNodesQuery_6638345083855817217(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "dataSeries", true);
  }
}
