package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.JComponent;
import com.xeiam.xchart.XChartPanel;
import org.campagnelab.mps.xchart.lib.HelperClasses.DoublesToCollection;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import com.xeiam.xchart.Chart;
import com.xeiam.xchart.ChartBuilder;
import com.xeiam.xchart.StyleManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class BarChart_Behavior {
  public static void init(SNode thisNode) {
  }

  public static JComponent virtual_getJComponent_5455899477603853704(SNode thisNode) {
    XChartPanel component = Chart_Behavior.call_getComponentInternal_7263499363579573717(thisNode);
    if (component != null) {
      component.resize(Chart_Behavior.call_getWidth_7263499363579584527(thisNode), Chart_Behavior.call_getHeight_7263499363579587829(thisNode));
      component.updateSeries("series", DoublesToCollection.toCollection(BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "x", false), "virtual_getDoubles_2202909375770410262", new Object[]{})), DoublesToCollection.toCollection(BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "heights", false), "virtual_getDoubles_2202909375770410262", new Object[]{})));
      return component;
    }
    Chart chart = new ChartBuilder().chartType(StyleManager.ChartType.Bar).width(Chart_Behavior.call_getWidth_7263499363579584527(thisNode)).height(Chart_Behavior.call_getHeight_7263499363579587829(thisNode)).theme(ChartStyle_Behavior.call_getTheme_7263499363580278109(SLinkOperations.getTarget(thisNode, "style", true))).title(SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "style", true), "title")).xAxisTitle(BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(thisNode, "x", false), "virtual_getColumnName_7335187880077215104", new Object[]{})).yAxisTitle(SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "style", true), "yAxisLabel")).build();
    chart.addSeries("series", DoublesToCollection.toCollection(BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "x", false), "virtual_getDoubles_2202909375770410262", new Object[]{})), DoublesToCollection.toCollection(BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "heights", false), "virtual_getDoubles_2202909375770410262", new Object[]{})));
    chart.getStyleManager().setLegendPosition(StyleManager.LegendPosition.InsideNE);
    component = new XChartPanel(chart);
    Chart_Behavior.call_putComponentInternal_7263499363579768301(thisNode, component);
    return component;
  }
}
