package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import com.xeiam.xchart.XChartPanel;
import jetbrains.mps.openapi.editor.EditorContext;

public class Chart_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2b6c6bL, 0x64cd2230006c3ecaL, "style"), SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x64cd2230006c3ea7L, "org.campagnelab.mps.XChart.structure.ChartStyle"))));
  }
  public static void call_addSeries_6638345083849971954(SNode thisNode, String seriesName, String... valueNames) {
    SNode series = Chart_Behavior.call_createNewSeries_6638345083852264294(thisNode, seriesName, valueNames);
    ListSequence.fromList(SLinkOperations.getChildren(thisNode, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2b6c6bL, 0x5c2023aeab55cf83L, "dataSeries"))).addElement(series);
  }
  public static SNode call_createNewSeries_6638345083852264294(SNode thisNode, String seriesName, String... valueNames) {
    SNode series = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x5c2023aeab55cfe9L, "org.campagnelab.mps.XChart.structure.DataSeries")));
    SPropertyOperations.set(series, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), seriesName);
    for (String value : valueNames) {
      SNode ref = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x5c2023aeab643748L, "org.campagnelab.mps.XChart.structure.DoublesReference")));
      SPropertyOperations.set(ref, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), value);
      ListSequence.fromList(SLinkOperations.getChildren(series, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x5c2023aeab55cfe9L, 0x5c2023aeab643743L, "values"))).addElement(ref);
    }
    return series;
  }
  public static SNode call_series_6638345083850011770(SNode thisNode, final String name) {
    return ListSequence.fromList(SLinkOperations.getChildren(thisNode, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2b6c6bL, 0x5c2023aeab55cf83L, "dataSeries"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals(name);
      }
    });
  }
  public static XChartPanel virtual_getComponentInternal_7263499363579573717(SNode thisNode) {
    XChartPanel component = null;

    try {
      component = (XChartPanel) thisNode.getUserObject("component");
    } catch (ClassCastException e) {
      component = null;
      thisNode.putUserObject("component", component);
    }
    return component;
  }
  public static void call_putComponentInternal_7263499363579768301(SNode thisNode, XChartPanel component) {
    thisNode.putUserObject("component", component);
  }
  public static int call_getWidth_7263499363579584527(SNode thisNode) {
    int width = Math.max(150, SPropertyOperations.getInteger(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2b6c6bL, 0x64cd2230006c3ecaL, "style")), MetaAdapterFactory.getProperty(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x64cd2230006c3ea7L, 0x49236d46f43192a9L, "width")));
    return width;
  }
  public static int call_getHeight_7263499363579587829(SNode thisNode) {
    int height = Math.max(150, SPropertyOperations.getInteger(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x1e924e67df2b6c6bL, 0x64cd2230006c3ecaL, "style")), MetaAdapterFactory.getProperty(0x5ec1cd3d0a504049L, 0xa8faae768d7baa25L, 0x64cd2230006c3ea7L, 0x49236d46f43192abL, "height")));
    return height;
  }
  public static void call_refresh_1507870905442172858(SNode thisNode, EditorContext editorContext) {
    Chart_Behavior.call_putComponentInternal_7263499363579768301(thisNode, null);
    editorContext.getEditorComponent().rebuildEditorContent();
  }
}
