package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.JComponent;
import org.campagnelab.mps.xchart.lib.HelperClasses.ChartPanel;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import com.xeiam.xchart.XChartPanel;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class Chart_Behavior {
  public static void init(SNode thisNode) {
  }

  public static JComponent virtual_getJComponent_5455899477603853704(SNode thisNode) {
    return new ChartPanel();
  }

  public static void call_refresh_3487897233198405658(SNode thisNode) {
    as_aym7s9_a0a0a2(BehaviorReflection.invokeVirtual(JComponent.class, thisNode, "virtual_getJComponent_5455899477603853704", new Object[]{}), ChartPanel.class).refresh(BehaviorReflection.invokeVirtual(XChartPanel.class, thisNode, "virtual_rebuildChart_7335187880077546450", new Object[]{}));
  }

  @Deprecated
  public static JComponent call_getJComponent_5455899477603853704(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(JComponent.class, thisNode, "virtual_getJComponent_5455899477603853704", new Object[]{});
  }

  @Deprecated
  public static JComponent callSuper_getJComponent_5455899477603853704(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(JComponent.class, SNodeOperations.cast(thisNode, "org.campagnelab.mps.XChart.structure.Chart"), callerConceptFqName, "virtual_getJComponent_5455899477603853704", new Class[]{SNode.class}, new Object[]{});
  }

  @Deprecated
  public static XChartPanel call_rebuildChart_7335187880077546450(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(XChartPanel.class, thisNode, "virtual_rebuildChart_7335187880077546450", new Object[]{});
  }

  @Deprecated
  public static XChartPanel callSuper_rebuildChart_7335187880077546450(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(XChartPanel.class, SNodeOperations.cast(thisNode, "org.campagnelab.mps.XChart.structure.Chart"), callerConceptFqName, "virtual_rebuildChart_7335187880077546450", new Class[]{SNode.class}, new Object[]{});
  }

  private static <T> T as_aym7s9_a0a0a2(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
