package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.xeiam.xchart.XChartPanel;
import jetbrains.mps.openapi.editor.EditorContext;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Chart_Behavior {
  public static void call_addSeries_6638345083849971954(SNode __thisNode__, String seriesName, String... valueNames) {
    Chart__BehaviorDescriptor.addSeries_id5Kw8UUFlDzM(__thisNode__, seriesName, valueNames);
  }
  public static SNode call_createNewSeries_6638345083852264294(SNode __thisNode__, String seriesName, String... valueNames) {
    return Chart__BehaviorDescriptor.createNewSeries_id5Kw8UUFupdA(__thisNode__, seriesName, valueNames);
  }
  public static SNode call_series_6638345083850011770(SNode __thisNode__, String name) {
    return Chart__BehaviorDescriptor.series_id5Kw8UUFlNhU(__thisNode__, name);
  }
  public static void call_putComponentInternal_7263499363579768301(SNode __thisNode__, XChartPanel component) {
    Chart__BehaviorDescriptor.putComponentInternal_id6jd8z00sERH(__thisNode__, component);
  }
  public static int call_getWidth_7263499363579584527(SNode __thisNode__) {
    return Chart__BehaviorDescriptor.getWidth_id6jd8z00rY0f(__thisNode__);
  }
  public static int call_getHeight_7263499363579587829(SNode __thisNode__) {
    return Chart__BehaviorDescriptor.getHeight_id6jd8z00rYNP(__thisNode__);
  }
  public static void call_refresh_1507870905442172858(SNode __thisNode__, EditorContext editorContext) {
    Chart__BehaviorDescriptor.refresh_id1jH29_Q1JYU(__thisNode__, editorContext);
  }
}
