package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.xeiam.xchart.XChartPanel;
import org.jetbrains.mps.openapi.model.SNode;
import javax.swing.JComponent;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class Chart_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public XChartPanel virtual_getComponentInternal_7263499363579573717(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.mps.XChart.structure.Chart";
  }

  public abstract JComponent virtual_getJComponent_5455899477603853704(SNode __thisNode__);
}
