package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import com.xeiam.xchart.StyleManager;

public class ChartStyle_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "width", "" + (400));
    SPropertyOperations.set(thisNode, "height", "" + (400));
    SPropertyOperations.set(thisNode, "title", "");
  }

  public static StyleManager.ChartTheme call_getTheme_7263499363580278109(SNode thisNode) {
    if (SPropertyOperations.getString_def(thisNode, "theme", "XChart").equals("GGPlot2".toString())) {
      return StyleManager.ChartTheme.GGPlot2;
    }
    if (SPropertyOperations.getString_def(thisNode, "theme", "XChart").equals("MatLab".toString())) {
      return StyleManager.ChartTheme.Matlab;
    }
    if (SPropertyOperations.getString_def(thisNode, "theme", "XChart").equals("XChart".toString())) {
      return StyleManager.ChartTheme.XChart;
    }
    return StyleManager.ChartTheme.XChart;
  }
}
