package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.campagnelab.mps.XChart.helpers.ColumnLoader;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class ColumnToDoubles_Behavior {
  public static void init(SNode thisNode) {
  }

  public static double[] virtual_getDoubles_2202909375770410262(SNode thisNode) {
    double[] cached = (double[]) thisNode.getUserObject(SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "file", false), "path") + SLinkOperations.getTarget(thisNode, "column", false));
    if (cached != null) {
      return cached;
    }
    String delimiter = "\t";
    {
      SNode dFile = SLinkOperations.getTarget(thisNode, "file", false);
      if (SNodeOperations.isInstanceOf(dFile, "org.campagnelab.mps.XChart.structure.DelimitedFile")) {
        delimiter = SPropertyOperations.getString(dFile, "delimitor");
      }
    }
    double[] result = ColumnLoader.load(SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "file", false), "path"), SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "column", false), "name"), delimiter);
    thisNode.putUserObject(SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "file", false), "path") + SLinkOperations.getTarget(thisNode, "column", false), result);
    return result;

  }

  public static String virtual_getColumnName_7335187880077215104(SNode thisNode) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "column", false), "name");
  }

  @Deprecated
  public static String call_getColumnName_4089421369806385653(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, thisNode, "virtual_getColumnName_7335187880077215104", new Object[]{});
  }

  @Deprecated
  public static String callSuper_getColumnName_4089421369806385653(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(String.class, SNodeOperations.cast(thisNode, "org.campagnelab.mps.XChart.structure.ColumnToDoubles"), callerConceptFqName, "virtual_getColumnName_7335187880077215104", new Class[]{SNode.class}, new Object[]{});
  }
}
