package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DataFile_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DataFile_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.mps.XChart.structure.DataFile";
  }
}
