package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */


public class DelimitedFile_BehaviorDescriptor extends DataFile_BehaviorDescriptor {
  public DelimitedFile_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.mps.XChart.structure.DelimitedFile";
  }
}
