package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.File;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.campagnelab.mps.XChart.helpers.ColumnLoader;
import java.io.IOException;
import org.campagnelab.mps.XChart.helpers.ColumnTypeGuesser;
import org.campagnelab.mps.XChart.helpers.Types;
import org.campagnelab.mps.XChart.helpers.TypeInstanceFinder;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class DelimitedFile_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String[] call_parseColumns_3597430320022539917(SNode thisNode) {
    BufferedReader reader = null;
    try {
      reader = new BufferedReader(new FileReader(new File(SPropertyOperations.getString(thisNode, "path"))));
      String header = reader.readLine();
      String[] columns = header.split(SPropertyOperations.getString(thisNode, "delimitor"));
      ColumnLoader.stripDoubleQuotes(columns);
      return columns;
    } catch (IOException e) {
      return null;
    } finally {
      try {
        if (reader != null) {
          reader.close();
        }
      } catch (IOException e) {
      }
    }
  }

  public static void call_assignColumnType_5010237105647900617(SNode thisNode, SNode column) {
    ColumnTypeGuesser guesser = new ColumnTypeGuesser(SPropertyOperations.getString(thisNode, "path"), SPropertyOperations.getString(column, "name"), SPropertyOperations.getString(thisNode, "delimitor"));
    Types type = guesser.guessValuesType();
    if (LOG.isInfoEnabled()) {
      LOG.info("returned type from guesser " + type.toString());
    }
    SNode typeRef = TypeInstanceFinder.lookup(type, SNodeOperations.getModel(thisNode));
    // for category, we need also to populate the members 
    if (type == Types.CATEGORY) {
      for (String value : guesser.getColumnUniqueValues()) {
        SNode newMember = SModelOperations.createNewNode(SNodeOperations.getModel(thisNode), null, "org.campagnelab.mps.XChart.types.structure.CategoryValue");
        SPropertyOperations.set(newMember, "name", value);
        ListSequence.fromList(SLinkOperations.getTargets(SNodeOperations.cast(typeRef, "org.campagnelab.mps.XChart.types.structure.ColumnCategoryType"), "members", true)).addElement(newMember);
      }
      SPropertyOperations.set(typeRef, "name", "Categories from " + SPropertyOperations.getString(column, "name"));
      SLinkOperations.setTarget(column, "category", SNodeOperations.cast(typeRef, "org.campagnelab.mps.XChart.types.structure.ColumnCategoryType"), true);
    }
    SLinkOperations.setTarget(column, "type", typeRef, false);
  }

  protected static Logger LOG = LogManager.getLogger(DelimitedFile_Behavior.class);
}
