package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class DelimitedFile_BehaviorDescriptor extends DataFile_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.mps.XChart.structure.DelimitedFile";
  }

}
