package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;

public class Doubles_Behavior {
  public static void init(SNode thisNode) {
  }
  public static int virtual_size_2202909375770434166(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), thisNode, "virtual_getDoubles_2202909375770410262", new Object[]{}).length;
  }
}
