package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FileRef_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FileRef_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.mps.XChart.structure.FileRef";
  }
}
