package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.scope.Scope;
import jetbrains.mps.lang.scopes.runtime.ScopeUtils;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class FileRef_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Scope virtual_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    return ScopeUtils.lazyParentScope(thisNode, kind);
  }

  public static Scope virtual_getScope_7722139651431880752(SNode thisNode, SNode kind, String role, int index) {
    return BehaviorReflection.invokeVirtual(Scope.class, thisNode, "virtual_getScope_3734116213129936182", new Object[]{kind, null});
  }

  @Deprecated
  public static Scope call_getScope_3734116213129936182(SNode thisNode, SNode kind, SNode child) {
    return BehaviorReflection.invokeVirtual(Scope.class, thisNode, "virtual_getScope_3734116213129936182", new Object[]{kind, child});
  }

  @Deprecated
  public static Scope callSuper_getScope_3734116213129936182(SNode thisNode, String callerConceptFqName, SNode kind, SNode child) {
    return BehaviorManager.getInstance().invokeSuper(Scope.class, SNodeOperations.cast(thisNode, "org.campagnelab.mps.XChart.structure.FileRef"), callerConceptFqName, "virtual_getScope_3734116213129936182", new Class[]{SNode.class, SNode.class, SNode.class}, new Object[]{kind, child});
  }

  @Deprecated
  public static Scope call_getScope_7722139651431880752(SNode thisNode, SNode kind, String role, int index) {
    return BehaviorReflection.invokeVirtual(Scope.class, thisNode, "virtual_getScope_7722139651431880752", new Object[]{kind, role, index});
  }

  @Deprecated
  public static Scope callSuper_getScope_7722139651431880752(SNode thisNode, String callerConceptFqName, SNode kind, String role, int index) {
    return BehaviorManager.getInstance().invokeSuper(Scope.class, SNodeOperations.cast(thisNode, "org.campagnelab.mps.XChart.structure.FileRef"), callerConceptFqName, "virtual_getScope_7722139651431880752", new Class[]{SNode.class, SNode.class, String.class, Integer.TYPE}, new Object[]{kind, role, index});
  }
}
