package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.xeiam.xchart.XChartPanel;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import com.xeiam.xchart.Chart;
import com.xeiam.xchart.ChartBuilder;
import com.xeiam.xchart.StyleManager;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import javax.swing.JComponent;

public class Histogram_Behavior {
  public static void init(SNode thisNode) {
  }

  public static XChartPanel virtual_rebuildChart_7335187880077546450(SNode thisNode) {
    if (SLinkOperations.getTarget(thisNode, "values", true) == null) {
      return null;
    }
    Chart chart = new ChartBuilder().chartType(StyleManager.ChartType.Bar).width(800).height(600).title("Score Histogram").xAxisTitle(BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(thisNode, "values", true), "virtual_getColumnName_7335187880077215104", new Object[]{})).yAxisTitle("Number").build();
    chart.addSeries("test 1", BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "values", true), "virtual_getDoubles_2202909375770410262", new Object[]{}), BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "values", true), "virtual_getDoubles_2202909375770410262", new Object[]{}));
    chart.getStyleManager().setLegendPosition(StyleManager.LegendPosition.InsideNE);
    return new XChartPanel(chart);
  }

  public static JComponent virtual_getJComponent_5455899477603853704(SNode thisNode) {
    Chart chart = new ChartBuilder().chartType(StyleManager.ChartType.Bar).width(800).height(600).title("Score Histogram").xAxisTitle(BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(thisNode, "values", true), "virtual_getColumnName_7335187880077215104", new Object[]{})).yAxisTitle("Number").build();
    chart.addSeries("test 1", BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "values", true), "virtual_getDoubles_2202909375770410262", new Object[]{}), BehaviorReflection.invokeVirtual((Class<double[]>) ((Class) Object.class), SLinkOperations.getTarget(thisNode, "values", true), "virtual_getDoubles_2202909375770410262", new Object[]{}));
    chart.getStyleManager().setLegendPosition(StyleManager.LegendPosition.InsideNE);
    return new XChartPanel(chart);
  }
}
