package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import com.xeiam.xchart.StyleManager;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Legend_Behavior {
  public static StyleManager.LegendPosition call_getPosition_3189972890131779785(SNode __thisNode__) {
    return Legend__BehaviorDescriptor.getPosition_id2L53R4Zr_39(__thisNode__);
  }
}
