package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Legend_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Legend_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.mps.XChart.structure.Legend";
  }
}
