package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */

import javax.swing.JComponent;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ScatterPlot_BehaviorDescriptor extends Chart_BehaviorDescriptor {
  public JComponent virtual_getJComponent_5455899477603853704(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.mps.XChart.structure.ScatterPlot";
  }

}
