package org.campagnelab.mps.XChart.behavior;

/*Generated by MPS */


public class Tsvfile_BehaviorDescriptor extends DelimitedFile_BehaviorDescriptor {
  public Tsvfile_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.mps.XChart.structure.Tsvfile";
  }
}
