package org.campagnelab.mps.xchart.helpers.HelperClasses;

/*Generated by MPS */

import javax.swing.JPanel;
import com.xeiam.xchart.XChartPanel;
import com.xeiam.xchart.Chart;

public class ChartPanel extends JPanel {
  /*package*/ XChartPanel chartPanel;

  public ChartPanel(Chart chart) {
    chartPanel = new XChartPanel(chart);
    this.add(chartPanel);
  }


}
