package org.campagnelab.mps.xchart.lib.HelperClasses;

/*Generated by MPS */

import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.Graphics;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class ChartPanel extends JPanel {
  /*package*/ JPanel chartPanel;

  public ChartPanel() {
    this.chartPanel = new JPanel();
    this.setBounds(0, 0, 800, 600);
    this.chartPanel.setBounds(0, 0, 800, 600);
    this.add(new JLabel("hello.."));
    this.add(chartPanel);
  }

  public void refresh(JPanel chartPanel) {
    if (LOG.isInfoEnabled()) {
      LOG.info("refreshing with " + chartPanel);
    }
    this.add(new JLabel("hello.."));
    if (chartPanel != null) {
      this.add(chartPanel);
      this.chartPanel.add(chartPanel);
    }
    this.repaint();
  }

  public void paintComponent(Graphics g) {
    int width = getWidth();
    int height = getHeight();
    super.paintComponent(g);
  }


  protected static Logger LOG = LogManager.getLogger(ChartPanel.class);
}
